## Generating own data in python

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [5]:
np.ndim(a)

1

In [6]:
b = np.array([[1,2],
              [2,3]])

In [7]:
b

array([[1, 2],
       [2, 3]])

In [8]:
np.ndim(b)

2

## Generating the data

In [9]:
ids = list(range(1,1001,1))

In [10]:
names = ['Utkarsh','Raman','Sarthak','Aditi','Rahul','Rakesh','Suresh','Ramesh']
names2 = np.random.choice(names,size=1000)

In [11]:
names2

array(['Raman', 'Ramesh', 'Rakesh', 'Ramesh', 'Raman', 'Suresh',
       'Utkarsh', 'Raman', 'Utkarsh', 'Suresh', 'Rahul', 'Sarthak',
       'Utkarsh', 'Raman', 'Rakesh', 'Rahul', 'Aditi', 'Rahul', 'Ramesh',
       'Raman', 'Rakesh', 'Rahul', 'Suresh', 'Rahul', 'Ramesh', 'Aditi',
       'Rahul', 'Utkarsh', 'Ramesh', 'Sarthak', 'Rahul', 'Sarthak',
       'Rahul', 'Aditi', 'Utkarsh', 'Ramesh', 'Ramesh', 'Suresh',
       'Suresh', 'Sarthak', 'Ramesh', 'Sarthak', 'Utkarsh', 'Suresh',
       'Suresh', 'Rahul', 'Utkarsh', 'Rakesh', 'Raman', 'Raman', 'Rakesh',
       'Rahul', 'Rahul', 'Ramesh', 'Rakesh', 'Aditi', 'Utkarsh',
       'Sarthak', 'Rakesh', 'Rakesh', 'Utkarsh', 'Ramesh', 'Ramesh',
       'Raman', 'Raman', 'Raman', 'Aditi', 'Aditi', 'Raman', 'Ramesh',
       'Raman', 'Raman', 'Ramesh', 'Utkarsh', 'Ramesh', 'Utkarsh',
       'Suresh', 'Sarthak', 'Rakesh', 'Sarthak', 'Suresh', 'Rakesh',
       'Aditi', 'Raman', 'Utkarsh', 'Sarthak', 'Aditi', 'Ramesh',
       'Sarthak', 'Suresh', 'Aditi

In [14]:
scores = np.random.normal(loc=70,scale=10,size=1000)

In [15]:
scores

array([66.53533012, 82.15418552, 76.83821021, 70.24371719, 77.89226392,
       72.59707428, 72.81771104, 70.78179387, 67.82256138, 67.60212594,
       74.50522368, 80.70758588, 71.57658306, 81.95978675, 54.73265422,
       49.83535344, 48.60842242, 74.87941962, 77.40939536, 80.80446655,
       87.78025599, 74.56883774, 75.0801766 , 62.42703817, 63.17465261,
       60.16111805, 79.73739449, 58.79272152, 77.3984663 , 61.85923062,
       73.81574894, 68.14924737, 77.85507104, 67.47467056, 64.13659566,
       78.87762637, 85.98849589, 71.77897979, 61.82742751, 70.53141599,
       72.39175316, 72.40607573, 63.49669264, 94.17983024, 68.83072388,
       68.43659297, 68.59280853, 76.18582764, 74.73385449, 67.19270602,
       69.31143267, 79.43506863, 88.75599288, 66.8912874 , 58.48276725,
       60.85465472, 88.33665416, 65.85987815, 68.36274722, 72.98851916,
       51.46736934, 82.51738651, 69.18510846, 63.38561168, 64.34779241,
       73.03865515, 82.0300459 , 59.80668943, 73.84267488, 52.91

In [16]:
import pandas as pd
dct = {'id':ids, 'names':names2,'score':scores}

In [18]:
import pandas as pd
df = pd.DataFrame(dct)
df

id    names      score
0       1    Raman  66.535330
1       2   Ramesh  82.154186
2       3   Rakesh  76.838210
3       4   Ramesh  70.243717
4       5    Raman  77.892264
..    ...      ...        ...
995   996   Rakesh  60.310768
996   997    Aditi  65.223110
997   998  Utkarsh  75.173828
998   999    Raman  72.101687
999  1000  Utkarsh  81.101024

[1000 rows x 3 columns]

In [19]:
df.to_csv('generated_data.csv',index=False)

### Generating integer numbers

In [20]:
c = np.random.randint(1,7,size=1000)

In [21]:
c

array([4, 6, 6, 2, 6, 2, 1, 6, 2, 2, 3, 3, 2, 4, 6, 3, 3, 6, 4, 2, 5, 4,
       2, 4, 3, 6, 1, 5, 2, 4, 3, 3, 6, 1, 2, 2, 1, 1, 2, 5, 6, 6, 6, 4,
       2, 6, 4, 1, 4, 6, 3, 6, 4, 1, 1, 3, 4, 3, 4, 3, 6, 4, 5, 4, 4, 5,
       5, 3, 2, 6, 5, 1, 3, 5, 4, 3, 4, 4, 5, 1, 1, 1, 5, 5, 4, 6, 3, 4,
       3, 3, 4, 1, 5, 5, 5, 6, 6, 1, 2, 5, 5, 4, 2, 2, 1, 3, 5, 4, 1, 5,
       4, 3, 3, 4, 1, 4, 3, 4, 3, 4, 4, 3, 3, 3, 5, 5, 5, 5, 2, 1, 3, 4,
       5, 2, 4, 2, 2, 2, 6, 5, 2, 1, 5, 3, 2, 1, 3, 2, 2, 2, 1, 1, 3, 5,
       6, 6, 5, 5, 1, 5, 5, 1, 6, 1, 5, 1, 4, 4, 5, 5, 1, 4, 5, 6, 1, 5,
       6, 3, 3, 6, 5, 4, 6, 2, 5, 2, 2, 3, 6, 3, 1, 1, 3, 3, 2, 2, 4, 6,
       2, 5, 3, 2, 3, 5, 1, 5, 2, 3, 1, 1, 1, 6, 6, 6, 3, 4, 4, 3, 6, 3,
       4, 1, 6, 4, 2, 6, 1, 1, 1, 3, 2, 6, 4, 5, 3, 1, 2, 3, 4, 2, 1, 3,
       4, 4, 6, 2, 3, 1, 2, 5, 4, 5, 1, 3, 6, 6, 1, 1, 3, 2, 3, 3, 6, 2,
       5, 2, 3, 1, 3, 5, 1, 4, 5, 4, 6, 5, 5, 2, 1, 5, 3, 5, 5, 2, 3, 5,
       3, 3, 1, 3, 2, 3, 6, 2, 3, 5, 1, 5, 2, 6, 3,